# Server port configuration
server:
  port: 8080

# DataSource configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_manage
    username: root
    password: minura

  # JPA Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true